version: '3'

services:

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # volumes:
    #   - db_data:/var/lib/postgresql/data/

    # adminer:
    #     image: adminer
    #     depends_on:
    #         - db
    #     ports:
    #         - 8082:8080

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_DEFAULT_EMAIL=admin@admin.home
    ports:
      - 8081:80
    depends_on:
      - db

  django:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: sleep infinity
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env.dev

  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/staticfiles:/app/staticfiles:cached
      - ./app/media:/app/media:cached
    ports:
      - 8080:80
    depends_on:
      - django

# volumes:
#   db_data:
#   staticfiles:
#   mediafiles:
